---
abstract: 'Handler for LWP::UserAgent that protects you from harm'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWPx-ParanoidHandler
no_index:
  directory:
    - inc
provides:
  LWPx::ParanoidHandler:
    file: lib/LWPx/ParanoidHandler.pm
    version: 0.04
requires:
  Exporter: 0
  LWP: 6
  Net::DNS::Paranoid: 0.04
  parent: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
